
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # Connection pool
    hikari:
      maximum-pool-size: 10
  # ORM
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Set 'validate' or 'none' in production
    show-sql: true  # Enable logging of SQL statements
logging:
  level:
    org.hibernate.SQL: debug  # Log SQL queries for debugging