
spring:
  flyway:  # temporary fix: flyway is important for database migration.
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sokoplace_db
    # username: ${POSTGRES_USER}
    username: "musembi"
    password: "my_password"
    driver-class-name: org.postgresql.Driver
    # Connection pool
    hikari:
      maximum-pool-size: 10
  # ORM
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Set 'validate' or 'none' in production
    show-sql: true  # Enable logging of SQL statements
logging:
  level:
    org.hibernate.SQL: debug  # Log SQL queries for debugging